
import java.io.FileReader;
import java.io.IOException;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ergastirio8.java
 *
 * Created on Dec 7, 2017, 11:34:58 AM
 */
/**
 *
 * @author user
 */
public class Ergastirio8 extends javax.swing.JFrame {

    /** Creates new form Ergastirio8 */
    
    String filename = "";
    public Ergastirio8() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpenDialog = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        OpenFileText = new javax.swing.JTextField();
        OpenButton = new javax.swing.JButton();
        OpenCancelButton = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        SaveFileText = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        AboutDialog = new javax.swing.JDialog();
        photoLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AboutTextArea = new javax.swing.JTextArea();
        message = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        OpenFile = new javax.swing.JMenuItem();
        CloseFile = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        SaveFile = new javax.swing.JMenuItem();
        SaveAsFile = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        ExitFile = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        CopyEdit = new javax.swing.JMenuItem();
        PasteEdit = new javax.swing.JMenuItem();
        CutEdit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        AboutHelp = new javax.swing.JMenuItem();

        OpenDialog.setTitle("Open File");

        jLabel2.setText("Oriste to onoma kai tin diadromi tou arxeiou");

        OpenButton.setText("Open");
        OpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenButtonActionPerformed(evt);
            }
        });

        OpenCancelButton.setText("Cancel");
        OpenCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OpenDialogLayout = new javax.swing.GroupLayout(OpenDialog.getContentPane());
        OpenDialog.getContentPane().setLayout(OpenDialogLayout);
        OpenDialogLayout.setHorizontalGroup(
            OpenDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpenDialogLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(OpenFileText, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addGap(75, 75, 75))
            .addGroup(OpenDialogLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel2)
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OpenDialogLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(OpenButton)
                .addGap(71, 71, 71)
                .addComponent(OpenCancelButton)
                .addGap(122, 122, 122))
        );
        OpenDialogLayout.setVerticalGroup(
            OpenDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpenDialogLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addComponent(OpenFileText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(OpenDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OpenCancelButton)
                    .addComponent(OpenButton))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jDialog2.setTitle("Save File");

        jLabel3.setText("Oriste to onoma kai tin diadromi tou arxeiou");

        SaveButton.setText("Save");

        CancelButton.setText("Cancel");

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(SaveButton)
                        .addGap(74, 74, 74)
                        .addComponent(CancelButton))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(SaveFileText, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog2Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(86, 86, 86))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel3)
                .addGap(46, 46, 46)
                .addComponent(SaveFileText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(CancelButton))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        AboutDialog.setTitle("Info Details");

        photoLabel.setText("NA valw mia foto");

        AboutTextArea.setColumns(20);
        AboutTextArea.setRows(5);
        AboutTextArea.setText("I ergasia auti egine apo ton theofanidi irakli \nstis 7 dekemvriou 2017\n");
        jScrollPane2.setViewportView(AboutTextArea);

        javax.swing.GroupLayout AboutDialogLayout = new javax.swing.GroupLayout(AboutDialog.getContentPane());
        AboutDialog.getContentPane().setLayout(AboutDialogLayout);
        AboutDialogLayout.setHorizontalGroup(
            AboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AboutDialogLayout.setVerticalGroup(
            AboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutDialogLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(AboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Menu Editor");

        message.setText("Message");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jMenu1.setMnemonic('F');
        jMenu1.setText("File");

        OpenFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        OpenFile.setMnemonic('o');
        OpenFile.setText("Open");
        OpenFile.setToolTipText("Open a Text File");
        OpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFileActionPerformed(evt);
            }
        });
        jMenu1.add(OpenFile);

        CloseFile.setMnemonic('C');
        CloseFile.setText("Close");
        CloseFile.setToolTipText("Close The File");
        jMenu1.add(CloseFile);
        jMenu1.add(jSeparator1);

        SaveFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SaveFile.setMnemonic('S');
        SaveFile.setText("Save");
        SaveFile.setToolTipText("Save The File");
        jMenu1.add(SaveFile);

        SaveAsFile.setMnemonic('A');
        SaveAsFile.setText("Save us");
        SaveAsFile.setToolTipText("Save a File With a New Name");
        SaveAsFile.setDisplayedMnemonicIndex(5);
        jMenu1.add(SaveAsFile);
        jMenu1.add(jSeparator2);

        ExitFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        ExitFile.setMnemonic('E');
        ExitFile.setText("Exit");
        ExitFile.setToolTipText("Close The Apliccation");
        jMenu1.add(ExitFile);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('E');
        jMenu2.setText("Edit");

        CopyEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        CopyEdit.setMnemonic('C');
        CopyEdit.setText("Copy");
        CopyEdit.setToolTipText("Copy the text");
        jMenu2.add(CopyEdit);

        PasteEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        PasteEdit.setMnemonic('P');
        PasteEdit.setText("Paste");
        PasteEdit.setToolTipText("Paste The Text");
        jMenu2.add(PasteEdit);

        CutEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        CutEdit.setMnemonic('x');
        CutEdit.setText("Cut");
        CutEdit.setToolTipText("Cut the text");
        jMenu2.add(CutEdit);

        jMenuBar1.add(jMenu2);

        jMenu3.setMnemonic('H');
        jMenu3.setText("Help");

        AboutHelp.setMnemonic('A');
        AboutHelp.setText("About");
        AboutHelp.setToolTipText("Info about the developer");
        jMenu3.add(AboutHelp);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void OpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFileActionPerformed
OpenDialog.setVisible(true);
OpenDialog.setSize(280,170);

}//GEN-LAST:event_OpenFileActionPerformed

private void OpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenButtonActionPerformed
    FileReader fw;
    filename = OpenFileText.getText();
    if(filename.length()==0)
    {
           jLabel2.setText("Oriste to onoma kai tin diadromi tou arxeiou pou thelete na aniksete");
           OpenDialog.setVisible(false);
           return;
           
    }
    
    try{
        fw= new FileReader(filename);
        jTextArea1.read(fw,null);
        fw.close();
         OpenDialog.setVisible(false);
         setTitle(filename);
    }
    catch(IOException exc)
            {
             jLabel2.setText("lathos onoma arxeiou");   
                return;
                
      
    }
    jLabel2.setText("To arxei fortothike swsta");
    

}//GEN-LAST:event_OpenButtonActionPerformed

private void OpenCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenCancelButtonActionPerformed
        OpenDialog.setVisible(false);
}//GEN-LAST:event_OpenCancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ergastirio8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ergastirio8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ergastirio8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ergastirio8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ergastirio8().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AboutDialog;
    private javax.swing.JMenuItem AboutHelp;
    private javax.swing.JTextArea AboutTextArea;
    private javax.swing.JButton CancelButton;
    private javax.swing.JMenuItem CloseFile;
    private javax.swing.JMenuItem CopyEdit;
    private javax.swing.JMenuItem CutEdit;
    private javax.swing.JMenuItem ExitFile;
    private javax.swing.JButton OpenButton;
    private javax.swing.JButton OpenCancelButton;
    private javax.swing.JDialog OpenDialog;
    private javax.swing.JMenuItem OpenFile;
    private javax.swing.JTextField OpenFileText;
    private javax.swing.JMenuItem PasteEdit;
    private javax.swing.JMenuItem SaveAsFile;
    private javax.swing.JButton SaveButton;
    private javax.swing.JMenuItem SaveFile;
    private javax.swing.JTextField SaveFileText;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel message;
    private javax.swing.JLabel photoLabel;
    // End of variables declaration//GEN-END:variables
}
