/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lalik
 */
public class Ergastirio4_1 extends javax.swing.JFrame {

    /**
     * Creates new form Ergastirio4_1
     */
    public Ergastirio4_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        LBass = new javax.swing.JLabel();
        LMidrange = new javax.swing.JLabel();
        LTremble = new javax.swing.JLabel();
        LBalance = new javax.swing.JLabel();
        LVolume = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SLMidrange = new javax.swing.JSlider();
        SLBass = new javax.swing.JSlider();
        SLTremble = new javax.swing.JSlider();
        SLBalance = new javax.swing.JSlider();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        SLVolume = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        LBass.setText("Bass");
        getContentPane().add(LBass, new java.awt.GridBagConstraints());

        LMidrange.setText("Midrange");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(LMidrange, gridBagConstraints);

        LTremble.setText("Tremble");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(LTremble, gridBagConstraints);

        LBalance.setText("Balance");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        getContentPane().add(LBalance, gridBagConstraints);

        LVolume.setText("Volume");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        getContentPane().add(LVolume, gridBagConstraints);

        jLabel6.setText("jLabel6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        getContentPane().add(jLabel6, gridBagConstraints);

        SLMidrange.setMajorTickSpacing(2);
        SLMidrange.setMaximum(10);
        SLMidrange.setMinimum(-10);
        SLMidrange.setMinorTickSpacing(1);
        SLMidrange.setPaintLabels(true);
        SLMidrange.setPaintTicks(true);
        SLMidrange.setValue(0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        getContentPane().add(SLMidrange, gridBagConstraints);

        SLBass.setMajorTickSpacing(2);
        SLBass.setMaximum(10);
        SLBass.setMinimum(-10);
        SLBass.setMinorTickSpacing(1);
        SLBass.setPaintLabels(true);
        SLBass.setPaintTicks(true);
        SLBass.setValue(0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        getContentPane().add(SLBass, gridBagConstraints);

        SLTremble.setMajorTickSpacing(2);
        SLTremble.setMaximum(10);
        SLTremble.setMinimum(-10);
        SLTremble.setMinorTickSpacing(1);
        SLTremble.setPaintLabels(true);
        SLTremble.setPaintTicks(true);
        SLTremble.setValue(0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        getContentPane().add(SLTremble, gridBagConstraints);

        SLBalance.setMajorTickSpacing(2);
        SLBalance.setMaximum(5);
        SLBalance.setMinimum(-5);
        SLBalance.setMinorTickSpacing(1);
        SLBalance.setPaintLabels(true);
        SLBalance.setPaintTicks(true);
        SLBalance.setValue(0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        getContentPane().add(SLBalance, gridBagConstraints);

        jRadioButton1.setText("jRadioButton1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jRadioButton1, gridBagConstraints);

        jRadioButton2.setText("jRadioButton2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jRadioButton2, gridBagConstraints);

        jRadioButton3.setText("jRadioButton3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jRadioButton3, gridBagConstraints);

        jButton1.setText("jButton1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        getContentPane().add(jButton1, gridBagConstraints);

        SLVolume.setMajorTickSpacing(1);
        SLVolume.setMaximum(10);
        SLVolume.setPaintLabels(true);
        SLVolume.setPaintTicks(true);
        SLVolume.setValue(0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        getContentPane().add(SLVolume, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ergastirio4_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ergastirio4_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ergastirio4_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ergastirio4_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ergastirio4_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBalance;
    private javax.swing.JLabel LBass;
    private javax.swing.JLabel LMidrange;
    private javax.swing.JLabel LTremble;
    private javax.swing.JLabel LVolume;
    private javax.swing.JSlider SLBalance;
    private javax.swing.JSlider SLBass;
    private javax.swing.JSlider SLMidrange;
    private javax.swing.JSlider SLTremble;
    private javax.swing.JSlider SLVolume;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
