/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ergastirio3_1.java
 *
 * Created on Oct 12, 2017, 11:41:48 AM
 */
/**
 *
 * @author user
 */
public class Ergastirio3_1 extends javax.swing.JFrame {

    /** Creates new form Ergastirio3_1 */
    public Ergastirio3_1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        kefalaio = new javax.swing.JLabel();
        epitokio = new javax.swing.JLabel();
        diarkeia = new javax.swing.JLabel();
        mhnes = new javax.swing.JLabel();
        kefalaiotext = new javax.swing.JTextField();
        epitokiotext = new javax.swing.JTextField();
        diarkeiatext = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        House_1 = new javax.swing.JRadioButton();
        House_2 = new javax.swing.JRadioButton();
        House_3 = new javax.swing.JRadioButton();
        axia = new javax.swing.JLabel();
        Timi = new javax.swing.JLabel();
        Ipologismos = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        DosiTimiLabel = new javax.swing.JLabel();
        EtiketaEnimerosis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agora_Spitiou");

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Stoixeia Daneiou"));

        kefalaio.setText("KEFALAIO");

        epitokio.setText("EPITOKIO");

        diarkeia.setText("DIARKEIA");

        mhnes.setText("MHNES");

        kefalaiotext.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        kefalaiotext.setText("0");

        epitokiotext.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        epitokiotext.setText("0");

        diarkeiatext.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        diarkeiatext.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(diarkeia)
                        .addGap(18, 18, 18)
                        .addComponent(diarkeiatext, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kefalaio)
                        .addGap(18, 18, 18)
                        .addComponent(kefalaiotext, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(epitokio)
                        .addGap(18, 18, 18)
                        .addComponent(epitokiotext, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(mhnes)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kefalaio)
                    .addComponent(kefalaiotext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(epitokiotext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(epitokio))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diarkeiatext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diarkeia)
                    .addComponent(mhnes))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("DIATHESIMA SPITIA"));

        buttonGroup1.add(House_1);
        House_1.setSelected(true);
        House_1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        House_1.setBorderPainted(true);
        House_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChatsworthHouse.jpg"))); // NOI18N
        House_1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ChatsworthHousePressed.jpg"))); // NOI18N
        House_1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ChatsworthHousePressed.jpg"))); // NOI18N
        House_1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ChatsworthHousePressed.jpg"))); // NOI18N
        House_1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                House_1ItemStateChanged(evt);
            }
        });
        House_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                House_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                House_1MouseExited(evt);
            }
        });

        buttonGroup1.add(House_2);
        House_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen_house.jpg"))); // NOI18N
        House_2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/queen_housePressed.jpg"))); // NOI18N
        House_2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/queen_housePressed.jpg"))); // NOI18N
        House_2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/queen_housePressed.jpg"))); // NOI18N
        House_2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                House_2ItemStateChanged(evt);
            }
        });
        House_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                House_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                House_2MouseExited(evt);
            }
        });

        buttonGroup1.add(House_3);
        House_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white_house.jpg"))); // NOI18N
        House_3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/white_housePressed.jpg"))); // NOI18N
        House_3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/white_housePressed.jpg"))); // NOI18N
        House_3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/white_housePressed.jpg"))); // NOI18N
        House_3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                House_3ItemStateChanged(evt);
            }
        });
        House_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                House_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                House_3MouseExited(evt);
            }
        });

        axia.setText("Aksia");

        Timi.setText("3.000.000");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(axia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Timi))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(House_3)
                        .addComponent(House_2)
                        .addComponent(House_1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(House_1)
                .addGap(26, 26, 26)
                .addComponent(House_2)
                .addGap(27, 27, 27)
                .addComponent(House_3)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(axia)
                    .addComponent(Timi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Ipologismos.setText("Ypologismos Dosis");
        Ipologismos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IpologismosActionPerformed(evt);
            }
        });

        jLabel7.setText("Dosi ana mina");

        DosiTimiLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(Ipologismos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel7)
                        .addGap(40, 40, 40)
                        .addComponent(DosiTimiLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(EtiketaEnimerosis)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(Ipologismos)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(DosiTimiLabel))
                        .addGap(47, 47, 47)
                        .addComponent(EtiketaEnimerosis)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void House_1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_House_1ItemStateChanged
        // TODO add your handling code here:
        Timi.setText("3.000.000");
        price = "3.000.000";
    }//GEN-LAST:event_House_1ItemStateChanged

    private void House_2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_House_2ItemStateChanged
        // TODO add your handling code here:
        Timi.setText("5.000.000");
        price = "5.000.000";
    }//GEN-LAST:event_House_2ItemStateChanged

    private void House_3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_House_3ItemStateChanged
        // TODO add your handling code here:
        Timi.setText("4.000.000");
        price = "4.000.000";
    }//GEN-LAST:event_House_3ItemStateChanged

    private void House_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_House_1MouseEntered
        // TODO add your handling code here:
        Timi.setText("3.000.000");
    }//GEN-LAST:event_House_1MouseEntered

    private void House_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_House_2MouseEntered
        // TODO add your handling code here:
        Timi.setText("5.000.000");
    }//GEN-LAST:event_House_2MouseEntered

    private void House_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_House_3MouseEntered
        // TODO add your handling code here:
        Timi.setText("4.000.000");
    }//GEN-LAST:event_House_3MouseEntered

    private void House_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_House_1MouseExited
        // TODO add your handling code here:
        Timi.setText(price);
    }//GEN-LAST:event_House_1MouseExited

    private void House_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_House_2MouseExited
        // TODO add your handling code here:
        Timi.setText(price);
    }//GEN-LAST:event_House_2MouseExited

    private void House_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_House_3MouseExited
        // TODO add your handling code here:
        Timi.setText(price);
    }//GEN-LAST:event_House_3MouseExited

    private void IpologismosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IpologismosActionPerformed
        // TODO add your handling code here:
        double kefalaioD = Double.valueOf(kefalaiotext.getText().replace(".",""));
        double epitokioD = Double.valueOf(epitokiotext.getText().replace(".",""));
        double diarkeiaD = Double.valueOf(diarkeiatext.getText().replace(".",""));
        double axiaD = Double.valueOf(price.replace(".",""));
        
        double daneio = axiaD -kefalaioD;
        if(daneio<=0)
            EtiketaEnimerosis.setText("Den xreiazetai daneio");
        else
        {
            EtiketaEnimerosis.setText("");
            double tokos= (daneio*epitokioD)/100;
            double daneiometoko = daneio + tokos;
            if(diarkeiaD>0) {
                double dosi = daneiometoko/diarkeiaD;
                DosiTimiLabel.setText(String.valueOf(dosi));
            } else
                DosiTimiLabel.setText("lathos diarkeia");
        }
    }//GEN-LAST:event_IpologismosActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ergastirio3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ergastirio3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ergastirio3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ergastirio3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ergastirio3_1().setVisible(true);
            }
        });
    }
    String price="3.000.000";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DosiTimiLabel;
    private javax.swing.JLabel EtiketaEnimerosis;
    private javax.swing.JRadioButton House_1;
    private javax.swing.JRadioButton House_2;
    private javax.swing.JRadioButton House_3;
    private javax.swing.JButton Ipologismos;
    private javax.swing.JLabel Timi;
    private javax.swing.JLabel axia;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel diarkeia;
    private javax.swing.JTextField diarkeiatext;
    private javax.swing.JLabel epitokio;
    private javax.swing.JTextField epitokiotext;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel kefalaio;
    private javax.swing.JTextField kefalaiotext;
    private javax.swing.JLabel mhnes;
    // End of variables declaration//GEN-END:variables
}
